### ISSUE TITLE
Version 1.1 Command line arguments don't work

### ISSUE THREAD

**Issue by tricead** [JULIELab/jufit#6]
Running with these arguments:
```jufit /Path/MRCONSO.RRF /Path/MRSTY.RRF ENG --mrconso```

returns the usage dialogue: 
```Usage:
 jufit <mrconso> <mrsty> <language> (--mrconso | --terms | --grounded | --complex) [--outFile=FILE] [--semanticGroup=GROUP]... [--rules=JSON] [--noFilter]
 jufit --help
 jufit --version
```

note the same paths work for me in version 1.0

**Comment by chlor** [comment]
Am 01.04.2020 um 20:36 schrieb Andrew Trice:
>
> Running with these arguments:
> |jufit /Path/MRCONSO.RRF /Path/MRSTY.RRF ENG --mrconso|
>
> returns the usage dialogue:
>
> |jufit <mrconso> <mrsty> <language> (--mrconso | --terms | --grounded 
> | --complex) [--outFile=FILE] [--semanticGroup=GROUP]... 
> [--rules=JSON] [--noFilter] jufit --help jufit --version``` note the 
> same paths work for me in version 1.0 |

Hi Andrew,

we have an error in our Readme file and will change it today. Sorry.

Did you build the executable JAR file (by maven) after downloading the 
program code?

Run

/java -jar/ <mrconso> <mrsty> <language> (--mrconso | --terms | 
--grounded | --complex) [--outFile=FILE] [--semanticGroup=GROUP]... 
[--rules=JSON] [--noFilter] NameOfJuFiTJar/.jar/

If you have more questions, don't hestitate and ask. :-)

Best Regards, Christina Lohr

**Comment by chlor** [comment]
Hi Andrew,
I have updated the code, details in Readme.md.
Best Regards, Christina
