### ISSUE TITLE
Add ability to filter by individual semantic values

### ISSUE THREAD

**Issue by tricead** [JULIELab/jufit#7]
The ability to filter by individual semantic values instead of group would be helpful for our research.

**Comment by chlor** [comment]
Hi Andrew,

sorry for my late answer. But, we changed the JuFiT Code and will upload the code today.
Did you mean Semantic Types of the UMLS like "T017" for "Anatomical Structure" from https://metamap.nlm.nih.gov/Docs/SemGroups_2018.txt
We have solved it an will upload the code. ;-)

Best Regards, Christina

**Comment by chlor** [comment]
A short solution to this issue is in the separated branch:
https://github.com/JULIELab/jufit/tree/SemanticTypes

**Comment by tricead** [comment]
Hey Christina, the example you used is correct. Thank you 😊 for the update
